# Generated by Django 4.0.5 on 2023-02-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_field', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=3000)),
            ],
        ),
    ]
